// <auto-generated />
using System;
using Bradgate.Migration.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Bradgate.Migration.Migrations
{
    [DbContext(typeof(MigrationContext))]
    class MigrationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bradgate.Migration.DbEntities.SeventyPercentClubEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsPlayer1Visitor");

                    b.Property<bool>("IsPlayer2Visitor");

                    b.Property<string>("Player1");

                    b.Property<string>("Player2");

                    b.Property<decimal>("Score");

                    b.Property<string>("SessionDescription");

                    b.HasKey("Id");

                    b.ToTable("SeventyPercentClubEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
